# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161006_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='current_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 6, 23, 38, 55, 233342, tzinfo=utc), null=True),
        ),
    ]
