# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161006_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 7, 1, 0, 34, 120375, tzinfo=utc), null=True),
        ),
    ]
