# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161006_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
