# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161006_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scanner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan', to='api.Scanner'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner', to='api.Location'),
        ),
    ]
